name: w_transport_example
version: 0.0.0
private: true

dev_dependencies:
  build_runner: '>=1.5.0 <2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
  collection: ^1.14.6
  dart_dev: ^2.0.0
  over_react: '>=1.30.2 <3.0.0'
  w_transport:
    path: ../

transformers:
  - over_react
