language: dart

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

stages:
  - quality
  - test

jobs:
  include:
    - stage: quality
      dart: 1.24.3
      script:
        - pub run dart_dev format --check
        - dartanalyzer lib test tool
        - cd example && pub get && dartanalyzer .; cd ..
        - pub run dependency_validator -i build_runner,build_test,build_web_compilers,browser,coverage,dart_style --exclude-dir=example

    - stage: quality
      dart: dev
      script:
        - dartanalyzer lib test tool
        - cd example && pub get && dartanalyzer .; cd ..
        - pub run dependency_validator -i build_runner,build_test,build_web_compilers,browser,coverage,dart_style --exclude-dir=example

    - stage: test
      dart: 1.24.3
      script: ./tool/travis.sh test:unit

    - stage: test
      dart: dev
      script: ./tool/travis.sh test:unit

    - stage: test
      dart: 1.24.3
      before_script: npm install
      script: ./tool/travis.sh test:integration

    - stage: test
      dart: dev
      before_script: npm install
      script: ./tool/travis.sh test:integration
