language: dart

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

dart:
  - 2.3.2
  - stable
  - dev

before_script:
  - npm install

script:
  - pub run dart_dev analyze
  - pub run dart_dev format --check
  - pub run dependency_validator -i build_runner,build_test,build_web_compilers,dart_style,pedantic
  - pub run dart_dev test -P travis
