language: dart

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

stages:
  - quality
  - test

jobs:
  include:
    - stage: quality
      dart: stable
      script:
        - pub run dart_dev format --check
        - pub run dart_dev analyze
        - pub run dependency_validator -i browser,coverage,dart_style

    - stage: quality
      dart: "2.0.0-dev.49.0"
      script:
        - pub run dart_dev format --check
        - pub run dart_dev analyze
        - pub run dependency_validator -i browser,coverage,dart_style

    - stage: test
      dart: stable
      script: ./tool/travis.sh test:unit

    - stage: test
      dart: "2.0.0-dev.49.0"
      script: ./tool/travis.sh test:unit

    - stage: test
      dart: stable
      before_script: npm install
      script: ./tool/travis.sh test:integration

    - stage: test
      dart: "2.0.0-dev.49.0"
      before_script: npm install
      script: ./tool/travis.sh test:integration
