targets:
  $default:
    builders:
      js_bridge|build:
        generate_for:
          - lib/src/http/http_body.dart
          - lib/src/http/http_client.dart
          - lib/src/http/requests.dart
          - lib/src/http/response.dart
