targets:
  $default:
    builders:
      build_vm_compilers|entrypoint:
        generate_for:
          include:
            - "test/**.vm_test.dart"
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "example/**.dart"
            - "test/**.browser_test.dart"
