name: w_transport
version: 0.0.1
author: Workiva
description: Ready to use transport abstractions over HttpRequest and HttpClientRequest.
dependencies:
  fluri: '>=1.0.0 <2.0.0'
dev_dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  args: '>=0.12.1 <0.14.0'
  browser: any
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: 796a265
  dart_codecov_generator:
    git:
      url: https://github.com/ekweible/dart_codecov_generator.git
      ref: 0.2.0
  http_server: '>=0.9.5+1 <0.10.0'
  mime: '>=0.9.3 <0.10.0'
  path: '>=1.3.5 <2.0.0'
  react: '>=0.6.1'
  shelf: '>=0.6.1+1 <0.7.0'
  test: '>=0.12.0 <0.13.0'
  uuid: 0.5.0