name: w_transport
version: 3.2.8

description: >
  Transport library for sending HTTP requests and opening WebSockets.
  Platform-independent with builtin support for browser and Dart VM (even
  supports SockJS). Includes mock utilities for testing.

homepage: https://github.com/Workiva/w_transport

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependency_overrides:
  dart_dev:
    git:
      url: https://github.com/Workiva/dart_dev.git
      ref: 3.0.0-wip__tools

dependencies:
  fluri: ^1.2.5
  http_parser: ^3.1.3
  meta: ^1.1.7
  mime: ^0.9.6+3
  sockjs_client:
    git:
      url: git://github.com/Workiva/sockjs-dart-client.git
      ref: 0.3.5
  sockjs_client_wrapper: ^1.0.8

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.8
  build_vm_compilers: ^1.0.3
  build_web_compilers: ^2.4.1
  collection: ^1.14.11
  dart_dev: ^2.1.0
  dart_style: ^1.2.8
  dependency_validator: ^1.2.4
  http_server: ^0.9.8+2
  logging: ^0.11.3+2
  mockito: ^4.1.0
  over_react: ^2.4.4
  pedantic: ^1.8.0
  test: ^1.6.4
  uuid: ^2.0.0
