name: w_transport
version: 3.2.8

description: >
  Transport library for sending HTTP requests and opening WebSockets.
  Platform-independent with builtin support for browser and Dart VM (even
  supports SockJS). Includes mock utilities for testing.

homepage: https://github.com/Workiva/w_transport

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>

environment:
  sdk: '>=1.24.3 <3.0.0'

dependencies:
  dart2_constant: ^1.0.1
  fluri: ^1.2.2
  http_parser: ^4.0.0
  meta: ^1.1.0
  mime: ^0.9.3
  sockjs_client:
    git:
      url: git@github.com:kyleferguson-wk/sockjs-dart-client.git
      ref: flutter-fix
  sockjs_client_wrapper:
    git:
      url: git://github.com/Workiva/sockjs_client_wrapper.git
      ref: flutter-fix-new

dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ^2.0.0
  build_web_compilers: ^2.16.5
  coverage: ^1.0.2
  dart_dev:
    git:
      url: git@github.com:kyleferguson-wk/dart_dev.git
      ref: master
  dart_style: ^1.0.8
  dependency_validator:
    git:
      url: git@github.com:kyleferguson-wk/dependency_validator.git
      ref: master
  http_server: ^0.9.6
  mockito: ">=2.0.2 <4.0.0"
  test: ">=0.12.30 <2.0.0"
  uuid: ^3.0.0

# Need to retain this transformers section until we drop Dart1 support completely.
transformers:
- test/pub_serve:
    $include: test/**_test.dart
