name: w_transport
version: 1.0.0
description: A fluent-style, platform-agnostic library with ready to use transport classes for sending and receiving data over HTTP.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/w_transport
dependencies:
  fluri: '>=1.0.0 <2.0.0'
dev_dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  args: '>=0.12.1 <0.14.0'
  browser: any
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: 796a265
  dart_codecov_generator:
    git:
      url: https://github.com/ekweible/dart_codecov_generator.git
      ref: 0.3.0
  dart_style: '>=0.1.8 <0.2.0'
  http_server: '>=0.9.5+1 <0.10.0'
  mime: '>=0.9.3 <0.10.0'
  mockito: '>=0.9.0 <0.10.0'
  path: '>=1.3.5 <2.0.0'
  react: '>=0.6.1 <0.7.0'
  shelf: '>=0.6.1+1 <0.7.0'
  test: '>=0.12.0 <0.13.0'
  uuid: '>=0.5.0 <0.6.0'
