name: w_transport
version: 2.9.7
description: >
  Platform-agnostic transport library for sending and receiving data over HTTP
  and WebSocket. HTTP support includes plain-text, JSON, form-data, and
  multipart data, as well as custom encoding. WebSocket support includes native
  WebSockets in the browser and the VM with the option to use SockJS in the
  browser.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/w_transport

environment:
  sdk: ">=1.9.0 <2.0.0"

dependencies:
  fluri: ^1.2.2
  http_parser: '>=1.0.0 <4.0.0'
  mime: ^0.9.3
  sockjs_client:
    git:
      url: https://github.com/Workiva/sockjs-dart-client.git
      ref: 0.3.2

dev_dependencies:
  ansicolor: ^0.0.9
  browser: ^0.10.0+2
  coverage: ^0.7.9
  dart_dev: ^1.7.7
  dart_style: ^1.0.6
  http_server: ^0.9.6
  mockito: ^2.0.2
  path: ^1.4.2
  react: ^0.6.1
  test: ^0.12.23+1
  uuid: ^0.5.3
